### ISSUE TITLE
Most common Junit assertion failures cannot be retried

### ISSUE THREAD

**Issue by anonygoose** [artsok/rerunner-jupiter#10]
The errors that rerunner-jupiter are currently capable of handling all extend from Exception.

This rules out handling for some of most common types of failure situations in tests: Junit's AssertionFailedError.

Can we alter the project so it handles everything that extends from Throwable instead, and make Throwable.class itself the default "exception" to be handled?

That way, by default any test failure will by handled without the need to always specify this behaviour.

**Comment by artsok** [comment]
Can y make Pull Request?

**Comment by anonygoose** [comment]
Sorry, this was sneakily in the fix for #11 .  Already merged.
