### ISSUE TITLE
Rerun failed parametrized tests 

### ISSUE THREAD

**Issue by geokh77** [artsok/rerunner-jupiter#13]
Hi 
I tried to use @RepeatedIfExceptionsTest for @ParameterizedTest. Unfortunately the failed tests did not rerun? Is it not possible to combine both?

Regards
George

**Comment by artsok** [comment]
Extension jar must to appears in maven central after 2-3 hours

**Comment by artsok** [comment]
Don't forget to push to the [star] if you like this JUnit 5 Extension. 👍

**Comment by artsok** [comment]
Sorry for delay.
