### ISSUE TITLE
New Maven release including feature #15

### ISSUE THREAD

**Issue by spanierm** [artsok/rerunner-jupiter#17]
Hi @artsok,

Can you please perform a new release to Maven Central with the changes from #15? The pull request was merged a month ago and we would really love to use it in our projects. This would also help with #8.

Thanks a lot and best regards,
Markus

**Comment by artsok** [comment]
Hi @spanierm 

Use this:
```xml
<dependency>
    <groupId>io.github.artsok</groupId>
    <artifactId>rerunner-jupiter</artifactId>
    <version>1.1.5</version>
</dependency>
```

**Comment by spanierm** [comment]
Great. Thanks a lot.
