### ISSUE TITLE
@ParameterizedRepeatedIfExceptionsTest will enter infinite loop if parameter `exceptions` is set and assertion fails

### ISSUE THREAD

**Issue by Forinil** [artsok/rerunner-jupiter#31]
The following test will run four times, failing three times and then succeeding:

```java
@ValueSource(ints = {1, 2})
@ParameterizedRepeatedIfExceptionsTest(repeats = 2)
 void testParameterizedRepeaterAssertionsFailure(int value) {
    assertThat(value, equalTo(2));
}
```

The same test with `exceptions` parameter set will run an infinite number of times, only failing the first time:
```java
@ValueSource(ints = {1, 2})
@ParameterizedRepeatedIfExceptionsTest(repeats = 2, exceptions = Exception.class)
void testParameterizedRepeaterAssertionsFailure(int value) {
    assertThat(value, equalTo(2));
}
```

Tested on Java 8 using version 2.0.1 of rerunner-jupiter library and Gradle 5.4.1.

**Comment by artsok** [comment]
Hi @Forinil 

I made PR to fix this problem, but I have not built a new version to central maven yet.

At first your test - the behavior is correct. Run a test with the first argument and then repeat it two times. Total runs 3 times for the first argument and 1 for the second argument.

Second your test - it was a bug in code. Thx a lot!

**Comment by artsok** [comment]
@Forinil 
Going to commit to maven central when will fix your another issue.

**Comment by artsok** [comment]
👍
