### ISSUE TITLE
Make Poll of exceptions to accept Throwables

### ISSUE THREAD

**Issue by serzhshakur** [artsok/rerunner-jupiter#7]
For now only classes that inherit from `java.lang.Exception.class` are accepted by `RepeatedIfExceptionsTest.extensions()` method. This is quite inconvenient as sometimes you want to also rerun test if AssertionError occurs. 
This is especially vital if you're working with [Selenide](https://github.com/codeborne/selenide) library which usually throws `com.codeborne.selenide.ex.ElementNotFound` exception if element not found which in turn inherits from `AssertionError` 
A minor changes in a code are required for this to be fixed (check [this row](https://github.com/artsok/rerunner-jupiter/blob/master/src/main/java/io/github/artsok/RepeatedIfExceptionsTest.java#L82) in a code)
```
Class<? extends Throwable>[] exceptions() default Exception.class;
```

**Comment by serzhshakur** [comment]
If you just allow I can do it myself and submit pull request

**Comment by serzhshakur** [comment]
Hi,
did you have time to check this?

**Comment by artsok** [comment]
Hi @serzhshakur 
Can you please send PR? Sorry for big delay!

**Comment by artsok** [comment]
already exist
