### ISSUE TITLE
match test as failed ONLY when LAST test-attempt failed

### ISSUE THREAD

**Issue by artsok** [artsok/rerunner-jupiter#8]
is it possible to update your great code to match test as failed ONLY when LAST test-attempt failed? I mean to throw e.g. abort exception when test is failing during repetition... This way when tests tun at any CI/CD (Jenkins, Bamboo) test suite will mark as Green when repetition passed.

From Roman Hesteric

**Comment by RomanHesteric** [comment]
any updates here?

**Comment by anonygoose** [comment]
@artsok this is a fairly serious problem.  Not  a lot of point using this library if it will always show a test failure if a retry has taken place.

**Comment by spanierm** [comment]
I just submitted a pull request to fix the issue, see #15, to solve this issue. As stated above, I would also love to see the changes to be able to use the library in any CI/CD automation.
I am happy to get any feedback :)

**Comment by RomanHesteric** [comment]
perfect ;o)

**Comment by artsok** [comment]
@RomanHesteric @spanierm Hi guys! Sorry for big delay.

Try this:
```
<dependency>
    <groupId>io.github.artsok</groupId>
    <artifactId>rerunner-jupiter</artifactId>
    <version>1.1.5</version>
</dependency>
```
